package com.example.pichincha.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@Data
@Builder(toBuilder = true)
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "BankAccount")
public class BankAccount {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName ="accountNumber")
    private String accountNumber;

    @DynamoDBAttribute(attributeName ="accountType")
    private String accountType;

    @DynamoDBAttribute(attributeName ="openingDate")
    private String openingDate;

    @DynamoDBAttribute(attributeName ="status")
    private String status;

    @DynamoDBAttribute(attributeName ="identificationNumber")
    private String identificationNumber;

    @DynamoDBAttribute(attributeName ="balance")
    private double balance;
}
