package com.example.pichincha.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder(toBuilder = true)
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "User")
public class User {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName ="firstName")
    private String firstName;

    @DynamoDBAttribute(attributeName ="lastName")
    private String lastName;

    @DynamoDBAttribute(attributeName ="identificationNumber")
    private String identificationNumber;

    @DynamoDBAttribute(attributeName ="phoneNumber")
    private String phoneNumber;

    @DynamoDBAttribute(attributeName ="address")
    private String address;

    @DynamoDBAttribute(attributeName ="gender")
    private String gender;

    @DynamoDBAttribute(attributeName ="birthdate")
    private String birthdate;

}
